export * from "./Home";
export * from "./Donate";
export * from "./Register";
export * from "./Book_Place";
export * from "./Reserve";
export * from "./View_List";
export * from "./Gallery";
export * from "./NextGallery";
export * from "./About";
